### ISSUE TITLE
Screenshot(s) for your readme

### ISSUE THREAD

**Issue by PySimpleGUI** [Uniminin/Splicer#3]
Hiya!

I've found that PySimpleGUI projects that have a screenshot of the GUI in their readme get a lot more traffic than those without.  Adding a screenshot is really easy (honest).  

You can use your GitHub issues to it.  Take an issue, like this one, and drag and drop an image file into the issue or you can even paste a screen-grab, like this one:

![image](https://user-images.githubusercontent.com/46163555/77687561-faa18400-6f74-11ea-9024-888c6c4e4456.png)

When you add it to the issue, you'll see a line of text that has a link to the image.  Add that line to your readme.md file and you'll have screenshots on your GitHub's homepage.

**Comment by Uniminin** [comment]
Thank you very much for your suggestion.

**Comment by PySimpleGUI** [comment]
YEA!! I like it!!  It's a really nice interface.  Well done 👋  Caught my attention right away.  Keep working at it!  Looks to me like you're doing great.  It's so nice to be able to make utilities that are exactly the way you want them to be.  And it's a wonderful way to learn.  Who knew GUI programming could be fun??
